spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 3112545232
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

# 火山AI配置
ark:
  api:
    key: b02fbb1a-c16d-4870-aa79-ba90a7b57aed
  base:
    url: https://ark.cn-beijing.volces.com/api/v3
  model:
    endpoint: doubao-seed-1-6-250615
